### ISSUE TITLE
Gif Sticker and Block Contacts

### ISSUE THREAD

**Issue by magrinstm** [kaiserdj/Stickerworld#6]
Hello I'm from Brazil.

1 ° I would like to know why the animated figures (gif) are a little accelerated?

2 ° And also, you can put an automatic block system for calls.

Thanks in advance.

P.S .: I really like your work, and I hope you keep bringing us updates.
I started studying programming after seeing your project.

**Comment by kaiserdj** [comment]
Hello, first of all, I am very happy that you like the project and I encourage you to study programming. It is very entertaining.

Regarding your first question, could you send me an example of a gif in which you notice that it accelerates?

And on the second question, if you refer to incoming calls from WhatsApp, the only thing I can do for now is detect that a call is being received and the data of that call (Who is calling you, if it is a group call, if it is a video call, etc), but I cannot interact with the call, since this project uses WhatsApp web as a base, and there is still no option implemented to be able to interact with the call.
So the only thing that could be done for now is, send an automatic message to all the people who call the bot.

Possibly, in the future I can do more things like hang up calls, etc ... but right now it is impossible

**Comment by magrinstm** [comment]
all the gifs and videos sent, which are transformed into animated figures, are accelerated, without exception.

and like, I tested it on different computers and cell phones to see if there would be any difference, but nothing has changed.

And about the calls, there are other projects that have this system, maybe you can take a look or get in touch with them.

they have this feature: MhankBarBar, YogaSakti, Tobz, ArugaZ, TobyG74

**Comment by kaiserdj** [comment]
On the issue of image size, I am working on a new version (restructuring all the code), and optimizing the process. I think that problem I have already fixed in this new version.

And about the calls, I have not found any bot that has that function, if you can send me a link or something, it would be of great help.

Thank you so much for everything

**Comment by ry2n711** [comment]
My name is Rayan from Saudi Arabia
I would like to thank you for the robot I liked it very much
I have a problem, the sticker is accelerating +
Hope you added rights to the sticker and auto responder
And thank you for your great effort

**Comment by magrinstm** [comment]
these are the projects that have this system:

- https://github.com/TobyG74/ElainaBOT
- https://github.com/ArugaZ/whatsapp-bot
- https://github.com/YogaSakti/imageToSticker
- https://github.com/Mhankbarbar/whatsapp-bot

**Comment by ry2n711** [comment]
But nothing is better than the @ kaiserdj project
With all respect, I tried the projects I mentioned but I prefer this one, but it needs to add other features like auto response after sending poster and poster rights.

**Comment by kaiserdj** [comment]
I'm still working on the new version, I hope I can publish it this weekend.

I will try to add new functions little by little, but before that I have to change the entire basis of the project to be able to work more comfortably and be able to do more things

And I'm glad you like it ❤️
